version: "3.7"
services:
  web:
    image: handuy1992/golang-crud
    ports:
      - "8181:8181"
    depends_on:
      - mysql
  mysql:
    image: handuy1992/golang-crud-mysql
    volumes:
      - /var/lib/mysql